### ISSUE TITLE
How json minify?

### ISSUE THREAD

**Issue by semiromid** [lanthaler/JsonLD#74]
How make json minify?

**Comment by lanthaler** [comment]
Could you please elaborate on what exactly you wanna do why and what you would expect from this library?On Feb 8, 2017 10:00 AM, semiromid <notifications@github.com> wrote:How make json minify?

**Comment by semiromid** [comment]
I want from 
```
    "item": {
      "@id": "https://example.com/books/authors",
      "name": "Authors",
    }
```
get 
`"item": {"@id": "https://example.com/books/authors","name": "Authors", "image":"http://example.com/images/icon-author.png"}`

I want compressed json

**Comment by lanthaler** [comment]
`JsonLD::toString($yourData, false)` does just that. The second parameter defines whether to pretty-print or not.
