### ISSUE TITLE
Build failure with latest PHP

### ISSUE THREAD

**Issue by LukasRos** [lanthaler/JsonLD#88]
Builds of my code that depends on JsonLD fail on Travis with the latest PHP nightly version (`PHP 7.3.0-dev (cli) (built: Jan 19 2018 04:19:11)`).

This is the error message:

`Fatal error: Cannot use stdClass as Object because 'Object' is a special class name in /home/travis/build/CloudObjects/RDFUtilities/vendor/ml/json-ld/ML/JsonLD/JsonLD.php on line 12`

**Comment by LukasRos** [comment]
Just realized that there's already a fix for that in #79. I'd appreciate if you could merge that PR.

**Comment by osma** [comment]
#92 has a better fix

**Comment by akuckartz** [comment]
Support for JSON-LD in PHP (and Drupal) could be improved...
