### ISSUE TITLE
Support for JSON-LD 1.1

### ISSUE THREAD

**Issue by IvoryHeart** [lanthaler/JsonLD#93]
The current library doesn't seem to be supporting [JSON-LD 1.1](https://json-ld.org/spec/latest/json-ld-api/) Spec.

Key words like `@version` are not supported in library. 

Is it proposed to be supported in the future?

**Comment by lanthaler** [comment]
JSON-LD 1.1 hasn't been standardized yet. Till that happens, this library won't be updated.

**Comment by someniatko** [comment]
@lanthaler Hi! It seems, JSON-LD 1.1 has been standartized 
https://www.w3.org/TR/json-ld11/
