### ISSUE TITLE
schema.org no longer returning application/ld+json

### ISSUE THREAD

**Issue by Sarke** [lanthaler/JsonLD#99]
When `FileGetContentsLoader::loadDocument('http://schema.org')` it now fails on line 105 because it's `text/html` and not json.

Not sure when that changed, but it pretty much breaks any schema lookup, unless it is cached.

**Comment by Sarke** [comment]
https://github.com/schemaorg/schemaorg/issues/2578#issuecomment-632227864

**Comment by lanthaler** [comment]
I just released version 1.2.0 with @tomgillett's fix that adds support for the alternate Link header that schema.org now uses.
